#---------------------------------#
#      General configuration      #
#---------------------------------#
skip_commits:
  files:
    - README.md
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/
#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 0.1.{build}
os: WMF 5
install:
  - ps: . .\AppVeyor\AppVeyorInstall.ps1

environment:
  GitHubServer: https://nuget.pkg.github.com/2Deep2Dive/index.json
  GitHubToken:
    secure: Gkp3fsNKmEhzYMZQ7sdwcTbjvejeBxIdss4yOM5r446mG00wKAbiZF/3qIugEwqw
  NugetServer: https://www.nuget.org/packages/manage/upload
  NugetToken:
    secure: 1xSdzIKmF3hKcNqqb1UKjplB1Sia3TRuA4lIIFL5sGyPEsTpz/0EHOBqPZPVRczr
  ModuleName: SyncADContacts
#---------------------------------#
#      Analyze configuration      #
#---------------------------------#
before_build:
  - ps: . .\AppVeyor\AppVeyorAnalyze.ps1

#---------------------------------#
#      build configuration        #
#---------------------------------#
build_script:
  - ps: . .\AppVeyor\AppVeyorBuild.ps1

#---------------------------------#
#      test configuration         #
#---------------------------------#
#test_script:
 # - ps: . .\AppVeyor\AppVeyorTest.ps1

#---------------------------------#
#      deployment configuration   #
#---------------------------------#
deploy:
- provider: NuGet
  server: https://www.nuget.org/packages/manage/upload
  api_key:
    secure: oy2gwcqr63eqo6fbij3anckjeqjjtltunk3tigr5cc4gay
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*(\.|\.s)nupkg/

- provider: GitHub
  server: https://nuget.pkg.github.com/2Deep2Dive/index.json
  artifact: /.nupkg/
  username:
  api_key:
    secure: $GitHub_Token

deploy_script:
  - ps: . .\AppVeyor\AppveyorDeploy.ps1

#---------------------------------#
#    notification configuration   #
#---------------------------------#
notifications:
- provider: Email
  to:
  - mohamed.eliwa@outlook.com
  subject: AppVeyor - Active_Directory Build Notification
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
